import "./PageBreadcrumb.css";

export default function PageBreadcrumb({ root, rootPath, current, items = [], onBack, className = "" }) {
  const editChitGroup = current === "Edit Chit Group" || current === "Add Chit Group";
  const displayedRoot = editChitGroup ? "Chit Groups" : root;
  const targetPath = editChitGroup ? "/chit-groups" : rootPath || ({ Customers: "/customers", "Chit Groups": "/chit-groups", "Loan Type": "/loan-types", "Loan Types": "/loan-types", "Holiday Master": "/holiday-master", "Active Loans": "/active-loans", "Collection History": "/collection-history", Reports: "/collection-report", Transactions: "/dashboard", Masters: "/masters" }[root] || "");
  const goToRoot = () => { if (editChitGroup || !onBack) { if (!targetPath) return; window.history.pushState({}, "", targetPath); window.dispatchEvent(new PopStateEvent("popstate")); return; } onBack(); };
  return <div className={`page-breadcrumb ${className}`.trim()}><button type="button" className="breadcrumb-back" onClick={goToRoot} aria-label={`Go to ${displayedRoot}`}><svg className="back-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12H5m7 7-7-7 7-7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></button>{targetPath ? <button type="button" className="breadcrumb-root breadcrumb-root-button" onClick={goToRoot}>{displayedRoot}</button> : <span className="breadcrumb-root">{displayedRoot}</span>}{items.map((item, index) => <span key={`${item.label}-${index}`} className="breadcrumb-item"><span className="breadcrumb-separator">/</span>{item.path ? <button type="button" className="breadcrumb-middle breadcrumb-root-button" onClick={() => { window.history.pushState({}, "", item.path); window.dispatchEvent(new PopStateEvent("popstate")); }}>{item.label}</button> : <span className="breadcrumb-middle">{item.label}</span>}</span>)}<span className="breadcrumb-separator">/</span><strong className="breadcrumb-current">{current}</strong></div>;
}
