# Generated by Django 5.2.17 on 2026-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customer_code', models.CharField(db_column='CustomerCode', db_index=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(db_column='CustomerName', db_index=True, max_length=150)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=20)),
                ('occupation', models.CharField(blank=True, db_column='Occupation', max_length=120)),
                ('monthly_income', models.DecimalField(blank=True, db_column='MonthlyIncome', decimal_places=2, max_digits=18, null=True)),
                ('primary_mobile', models.CharField(db_column='Phone', db_index=True, max_length=15, unique=True)),
                ('alternate_mobile', models.CharField(blank=True, db_column='AlternatePhone', max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, db_column='WhatsApp', max_length=15)),
                ('is_whatsapp_same_as_phone', models.BooleanField(db_column='IsWhatsappSameAsPhone', default=False)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254)),
                ('role', models.CharField(choices=[('LENDER', 'Lender'), ('BORROWER', 'Borrower'), ('BOTH', 'Both')], db_column='CustomerRole', db_index=True, max_length=10)),
                ('address', models.TextField(blank=True, db_column='Address')),
                ('city', models.CharField(blank=True, db_column='City', max_length=80)),
                ('district', models.CharField(blank=True, db_column='District', max_length=80)),
                ('state', models.CharField(blank=True, db_column='State', max_length=80)),
                ('country', models.CharField(blank=True, db_column='Country', default='India', max_length=80)),
                ('pincode', models.CharField(blank=True, db_column='Pincode', max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, db_column='Aadhaar', db_index=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, db_column='PAN', db_index=True, max_length=10)),
                ('is_active', models.BooleanField(db_column='IsActive', db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreateDate')),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'Customer_tbl',
                'ordering': ['full_name'],
            },
        ),
    ]
