# Generated by Django 5.2.17 on 2026-10-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_location_masters'),
        ('finance', '0020_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, db_column='GroupID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='finance.group'),
        ),
    ]
