# Generated by Django 5.2.17 on 2026-10-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_group'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
    ]
