# Generated by Django 5.2.17 on 2026-08-08 11:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_business_masters(apps, schema_editor):
    LoanType = apps.get_model("finance", "LoanType")
    for name in ("Chit", "Interest"):
        LoanType.objects.get_or_create(name=name, defaults={"is_active": True})
    LoanInstallment = apps.get_model("finance", "LoanInstallment")
    for name, code in (("Daily", "DAILY"), ("Weekly", "WEEKLY"), ("Monthly", "MONTHLY"), ("Annual", "ANNUAL"), ("100 Days", "100DAYS"), ("Other", "OTHER")):
        LoanInstallment.objects.update_or_create(name=name, defaults={"code": code, "is_active": True})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitGroup',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='ChitGroupCode', max_length=20, unique=True)),
                ('name', models.CharField(db_column='ChitGroupName', max_length=150)),
                ('duration_type', models.CharField(db_column='DurationType', max_length=10)),
                ('duration', models.PositiveIntegerField(db_column='Duration')),
                ('collection_day', models.PositiveSmallIntegerField(blank=True, db_column='CollectionDay', null=True)),
                ('collection_month', models.PositiveSmallIntegerField(blank=True, db_column='CollectionMonth', null=True)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'ChitGroup_tbl',
            },
        ),
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(db_column='HolidayDate', unique=True)),
                ('holiday_name', models.CharField(db_column='HolidayName', max_length=150)),
                ('holiday_type', models.CharField(db_column='HolidayType', max_length=30)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'HolidayMaster_tbl',
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='InstallmentName', max_length=100, unique=True)),
                ('code', models.CharField(db_column='InstallmentCode', max_length=30, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'LoanInstallment_tbl',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='LoanTypeName', max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'LoanType_tbl',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoanDetails',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('loan_no', models.CharField(blank=True, db_column='LoanNo', max_length=30, null=True, unique=True)),
                ('loan_amount', models.DecimalField(db_column='LoanAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('loan_start_date', models.DateField(db_column='LoanStartDate')),
                ('loan_end_date', models.DateField(blank=True, db_column='LoanEndDate', null=True)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('penalty_amount', models.DecimalField(db_column='PenaltyAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('outstanding_amount', models.DecimalField(db_column='OutstandingAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('loan_status', models.CharField(db_column='LoanStatus', default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='customer_loans', to='customers.customer')),
                ('loan_type', models.ForeignKey(db_column='LoanTypeID', on_delete=django.db.models.deletion.PROTECT, to='finance.loantype')),
            ],
            options={
                'db_table': 'CustomerLoanDetails_tbl',
            },
        ),
        migrations.CreateModel(
            name='CustomerChitDetails',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('include_sunday', models.BooleanField(db_column='IncludeSunday', default=False)),
                ('chit_group', models.ForeignKey(db_column='ChitGroupID', on_delete=django.db.models.deletion.PROTECT, to='finance.chitgroup')),
                ('loan', models.OneToOneField(db_column='CustomerLoanDetailsID', on_delete=django.db.models.deletion.CASCADE, related_name='chit_details', to='finance.customerloandetails')),
            ],
            options={
                'db_table': 'CustomerChitDetails_tbl',
            },
        ),
        migrations.CreateModel(
            name='InterestDetails',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(db_column='PrincipalAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('interest_percentage', models.DecimalField(db_column='InterestPercentage', decimal_places=3, default=0, max_digits=8)),
                ('interest_amount', models.DecimalField(db_column='InterestAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_payable_amount', models.DecimalField(db_column='TotalPayableAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('duration_value', models.PositiveIntegerField(db_column='DurationValue', default=0)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('collection_day', models.PositiveSmallIntegerField(blank=True, db_column='CollectionDay', null=True)),
                ('collection_date', models.DateField(blank=True, db_column='CollectionDate', null=True)),
                ('collection_month', models.PositiveSmallIntegerField(blank=True, db_column='CollectionMonth', null=True)),
                ('installment_count', models.PositiveIntegerField(db_column='InstallmentCount', default=0)),
                ('installment_amount', models.DecimalField(db_column='InstallmentAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('penalty_percentage', models.DecimalField(db_column='PenaltyPercentage', decimal_places=3, default=0, max_digits=8)),
                ('penalty_type', models.CharField(blank=True, db_column='PenaltyType', max_length=30)),
                ('grace_days', models.PositiveIntegerField(db_column='GraceDays', default=0)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('outstanding_amount', models.DecimalField(db_column='OutstandingAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('loan', models.OneToOneField(db_column='CustomerLoanDetailsID', on_delete=django.db.models.deletion.CASCADE, related_name='interest_details', to='finance.customerloandetails')),
                ('loan_installment', models.ForeignKey(db_column='LoanInstallmentID', on_delete=django.db.models.deletion.PROTECT, to='finance.loaninstallment')),
            ],
            options={
                'db_table': 'InterestDetails_tbl',
            },
        ),
        migrations.CreateModel(
            name='ChitGroupInstallmentDetail',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(db_column='InstallmentNo')),
                ('schedule_value', models.CharField(db_column='ScheduleValue', max_length=100)),
                ('installment_amount', models.DecimalField(db_column='InstallmentAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('group', models.ForeignKey(db_column='ChitGroupID', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.chitgroup')),
            ],
            options={
                'db_table': 'ChitGroup_InstallmentDetails_tbl',
                'constraints': [models.UniqueConstraint(fields=('group', 'installment_number'), name='uniq_chit_group_installment')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoanInstallmentDetails',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(db_column='InstallmentNo')),
                ('due_date', models.DateField(db_column='DueDate')),
                ('installment_amount', models.DecimalField(db_column='InstallmentAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('penalty_amount', models.DecimalField(db_column='PenaltyAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('outstanding_amount', models.DecimalField(db_column='OutstandingAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payment_status', models.CharField(db_column='PaymentStatus', default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, db_column='PaidDate', null=True)),
                ('loan', models.ForeignKey(db_column='CustomerLoanDetailsID', on_delete=django.db.models.deletion.CASCADE, related_name='installment_details', to='finance.customerloandetails')),
            ],
            options={
                'db_table': 'CustomerLoanInstallmentDetails_tbl',
                'ordering': ('due_date', 'installment_number'),
                'constraints': [models.UniqueConstraint(fields=('loan', 'installment_number'), name='uniq_customer_loan_installment')],
            },
        ),
        migrations.CreateModel(
            name='LoanHolidaySettings',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('include_in_schedule', models.BooleanField(db_column='IncludeInSchedule', default=False)),
                ('holiday', models.ForeignKey(db_column='HolidayID', on_delete=django.db.models.deletion.PROTECT, to='finance.holidaymaster')),
                ('loan', models.ForeignKey(db_column='CustomerLoanDetailsID', on_delete=django.db.models.deletion.CASCADE, related_name='holiday_settings', to='finance.customerloandetails')),
            ],
            options={
                'db_table': 'LoanHolidaySettings_tbl',
                'constraints': [models.UniqueConstraint(fields=('loan', 'holiday'), name='uniq_loan_holiday_setting')],
            },
        ),
        migrations.RunPython(seed_business_masters, migrations.RunPython.noop),
    ]
