# Generated by Django 5.2.17 on 2026-08-08 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitgroup',
            name='total_amount',
            field=models.DecimalField(db_column='TotalAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
