# Generated by Django 5.2.17 on 2026-08-11 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_collectiontransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentTypeMaster',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='AdjustmentTypeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='AdjustmentTypeName', max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'AdjustmentTypeMaster_tbl',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='adjustment_amount',
            field=models.DecimalField(db_column='AdjustmentAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, db_column='AdjustmentType', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='bank_name',
            field=models.CharField(blank=True, db_column='BankName', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='cheque_date',
            field=models.DateField(blank=True, db_column='ChequeDate', null=True),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='cheque_number',
            field=models.CharField(blank=True, db_column='ChequeNumber', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='discount_amount',
            field=models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='upi_id',
            field=models.CharField(blank=True, db_column='UpiID', default='', max_length=100),
        ),
    ]
