# Generated by Django 5.2.17 on 2026-09-23 07:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


def preserve_current_rates(apps, schema_editor):
    Mortgage = apps.get_model('finance', 'Mortgage')
    Rate = apps.get_model('finance', 'MortgageRate')
    Unit = apps.get_model('finance', 'MortgageUnit')
    alias = schema_editor.connection.alias
    for name in ('Gram', 'No', 'Pcs'):
        Unit.objects.using(alias).get_or_create(name=name)
    for product in Mortgage.objects.using(alias).all():
        Rate.objects.using(alias).get_or_create(mortgage_id=product.id, date=timezone.localdate(), defaults={'rate': product.current_rate})
        if product.unit:
            Unit.objects.using(alias).get_or_create(name=product.unit)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_mortgage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='collection_date',
            field=models.DateField(blank=True, db_column='CollectionDate', null=True),
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='start_date',
            field=models.DateField(blank=True, db_column='StartDate', null=True),
        ),
        migrations.AddField(
            model_name='holidaymaster',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='holidaymaster',
            name='state_region',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='MortgageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.mortgage')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'constraints': [models.UniqueConstraint(fields=('mortgage', 'date'), name='uniq_mortgage_rate_date')],
            },
        ),
        migrations.RunPython(preserve_current_rates, migrations.RunPython.noop),
    ]
