# Generated by Django 5.2.17 on 2026-09-24 09:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def preserve_existing_loans(apps, schema_editor):
    Loan = apps.get_model('finance', 'CustomerLoanDetails')
    Sequence = apps.get_model('finance', 'LoanDocumentSequence')
    Mortgage = apps.get_model('finance', 'MortgageLoanDetails')
    History = apps.get_model('finance', 'MortgageLoanHistory')
    alias = schema_editor.connection.alias
    counters = {'CH': 0, 'IN': 0, 'M': 0}
    for loan in Loan.objects.using(alias).select_related('loan_type', 'customer').order_by('id'):
        prefix = {'chit': 'CH', 'interest': 'IN', 'mortgage': 'M'}.get(loan.loan_type.name.strip().lower(), f'L{loan.loan_type_id}')
        counters[prefix] = counters.get(prefix, 0) + 1
        loan.doc_no = f'{prefix}-{counters[prefix]:04d}'
        # Use the recorded creation date where available; do not change start dates.
        loan.application_date = django.utils.timezone.localdate(loan.create_date) if loan.create_date else loan.loan_start_date
        loan.save(using=alias, update_fields=['doc_no', 'application_date'])
        mortgage = Mortgage.objects.using(alias).filter(loan_id=loan.pk).first()
        if mortgage:
            snapshot = {field: str(getattr(mortgage, field)) if getattr(mortgage, field) is not None else None
                        for field in ('product_id', 'product_name', 'unit', 'quantity', 'current_rate',
                                      'market_value', 'loan_amount', 'interest_percentage', 'daily_interest_amount')}
            snapshot.update(customer_id=loan.customer_id, customer_name=loan.customer.full_name,
                            loan_no=loan.loan_no, application_date=str(loan.application_date),
                            start_date=str(loan.loan_start_date), total_amount=str(loan.total_amount))
            History.objects.using(alias).create(loan_id=loan.pk, doc_no=loan.doc_no,
                customer_name=loan.customer.full_name, action='EXISTING', snapshot=snapshot)
    for prefix, value in counters.items():
        Sequence.objects.using(alias).update_or_create(prefix=prefix, defaults={'last_value': value})


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_mortgage_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('name', models.CharField(max_length=150)),
                ('group', models.CharField(choices=[('Sundry Debtors', 'Sundry Debtors'), ('Sundry Creditors', 'Sundry Creditors'), ('Indirect Expense', 'Indirect Expense'), ('Direct Expense', 'Direct Expense'), ('Income', 'Income'), ('Cash in Hand', 'Cash in Hand'), ('Bank Accounts', 'Bank Accounts')], max_length=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentSequence',
            fields=[
                ('prefix', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customerloandetails',
            name='application_date',
            field=models.DateField(db_column='ApplicationDate', default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='customerloandetails',
            name='doc_no',
            field=models.CharField(db_column='DocNo', default='', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='mortgageloandetails',
            name='product',
            field=models.ForeignKey(blank=True, db_column='MortgageID', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.mortgage'),
        ),
        migrations.AlterField(
            model_name='mortgageloandetails',
            name='product_name',
            field=models.CharField(blank=True, db_column='ProductName', max_length=150),
        ),
        migrations.AlterField(
            model_name='mortgageloandetails',
            name='quantity',
            field=models.DecimalField(blank=True, db_column='Quantity', decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageloandetails',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=50),
        ),
        migrations.CreateModel(
            name='MortgageLoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('EXISTING', 'Existing')], max_length=10)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('snapshot', models.JSONField()),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_history', to='finance.customerloandetails')),
            ],
            options={
                'ordering': ('-recorded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('accounts', models.CharField(choices=[('Card', 'Card'), ('Credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('NEFT', 'NEFT/IMPS/RGST')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('transaction_utr', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.ledger')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.RunPython(preserve_existing_loans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customerloandetails', name='doc_no',
            field=models.CharField(db_column='DocNo', default='', editable=False, max_length=30, unique=True),
        ),
    ]
