# Generated by Django 5.2.17 on 2026-09-25 10:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_ledger_loandocumentsequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontransaction',
            name='account',
            field=models.ForeignKey(blank=True, db_column='AccountLedgerID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_transactions', to='finance.ledger'),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='ledger_amount',
            field=models.DecimalField(db_column='LedgerAmount', decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='ledger_group',
            field=models.CharField(blank=True, choices=[('Sundry Debtors', 'Sundry Debtors'), ('Sundry Creditors', 'Sundry Creditors'), ('Indirect Expense', 'Indirect Expense'), ('Direct Expense', 'Direct Expense'), ('Income', 'Income')], db_column='LedgerGroup', default='', max_length=30),
        ),
    ]
