# Generated by Django 5.2.17 on 2026-09-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_collectiontransaction_account_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_payments', to='finance.ledger'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='ledger_group',
            field=models.CharField(blank=True, choices=[('Sundry Debtors', 'Sundry Debtors'), ('Sundry Creditors', 'Sundry Creditors'), ('Indirect Expense', 'Indirect Expense'), ('Direct Expense', 'Direct Expense'), ('Income', 'Income')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='accounts',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('Credit', 'Credit')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.ledger'),
        ),
    ]
