# Generated by Django 5.2.17 on 2026-09-25 11:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_payment_entry_ledger_account_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('installment', models.ForeignKey(db_column='InstallmentID', on_delete=django.db.models.deletion.PROTECT, related_name='collection_allocations', to='finance.customerloaninstallmentdetails')),
                ('transaction', models.ForeignKey(db_column='CollectionTransactionID', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.collectiontransaction')),
            ],
            options={
                'db_table': 'CollectionAllocation_tbl',
                'ordering': ('id',),
            },
        ),
    ]
