# Generated by Django 5.2.17 on 2026-09-26 00:00

from django.db import migrations, models


def seed_product_groups(apps, schema_editor):
    ProductGroup = apps.get_model('finance', 'MortgageProductGroup')
    alias = schema_editor.connection.alias
    for name in ('Gold', 'Silver', 'Brass', 'Bronze'):
        ProductGroup.objects.using(alias).get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_collection_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mortgage',
            name='product_group',
            field=models.CharField(blank=True, db_column='ProductGroup', default='', max_length=50),
        ),
        migrations.RunPython(seed_product_groups, migrations.RunPython.noop),
    ]
