# Generated by Django 5.2.17 on 2026-09-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_mortgage_product_group'),
        ('customers', '0002_location_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='ledger',
            field=models.ForeignKey(blank=True, db_column='LedgerID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_collections', to='finance.ledger'),
        ),
    ]
