# Generated by Django 5.2.17 on 2026-10-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_ledger_customer_collectiontransaction_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='GroupName', max_length=150)),
                ('is_system', models.BooleanField(db_column='IsSystem', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('parent', models.ForeignKey(blank=True, db_column='ParentGroupID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.group')),
            ],
            options={
                'db_table': 'Group_tbl',
                'ordering': ('name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='uniq_group_parent_name')],
            },
        ),
    ]
