# Generated by Django 5.2.17 on 2026-10-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_group'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitgroup',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='group',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='holidaymaster',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='group_detail',
            field=models.ForeignKey(blank=True, db_column='GroupDetailID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers_detail', to='finance.group'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
    ]
