# Generated by Django 5.2.17 on 2026-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_fix_cash_in_hand_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='group',
            field=models.CharField(choices=[('Sundry Debtors', 'Sundry Debtors'), ('Sundry Creditors', 'Sundry Creditors'), ('Indirect Expense', 'Indirect Expense'), ('Direct Expense', 'Direct Expense'), ('Income', 'Income'), ('Cash-in-Hand', 'Cash-in-Hand'), ('Bank Accounts', 'Bank Accounts')], max_length=30),
        ),
    ]
