# Generated by Django 5.2.17 on 2026-10-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_ledger_group'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontransaction',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='customerloandetails',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='done_by_staff',
            field=models.ForeignKey(blank=True, db_column='DoneByStaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff'),
        ),
    ]
