# Generated by Django 5.2.17 on 2026-10-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_collectiontransaction_done_by_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nature',
            field=models.CharField(blank=True, choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_column='Nature', default='', max_length=10),
        ),
    ]
