# Generated by Django 5.2.17 on 2026-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('staff_name', models.CharField(db_index=True, max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=15)),
                ('aadhaar_number', models.CharField(blank=True, db_index=True, max_length=12)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'db_table': 'staff_tbl',
                'ordering': ['staff_name'],
            },
        ),
    ]
